"""
curve_fitting.py

Phase 4.5B: fits Nelson-Siegel (4 parameters) and Svensson (6 parameters)
parametric curves to the BOOTSTRAPPED ZERO curve from Part A
(models/bootstrap.py), giving a smooth, continuous curve described by a
handful of interpretable numbers instead of ~80 discrete grid points.

WHY FIT THE ZERO CURVE, NOT THE PAR CURVE. Fitting a parametric model
directly to a par yield curve is the more common choice in practice, but
a less principled one here: this project already built a bootstrapped
zero curve specifically to get a theoretically cleaner discounting basis
(docs/phase_4_5a_documentation.md), and a parametric model's whole
purpose is to describe the SHAPE of that same no-arbitrage-consistent
object smoothly -- fitting it to the par curve instead would reintroduce
exactly the coupon-mixing distortion Part A's zero curve exists to remove
(Part A's own §1 "coupon effect" finding). Every fit in this module
therefore takes a models.bootstrap.bootstrap_zero_curve() result (columns
[maturity_years, zero_rate]) as its target, never a par curve directly.

INHERITS PART A'S OWN CAVEAT. The zero curve fit here was itself built by
treating MOF's fitted-YTM series as a par curve (a documented, measured
simplification -- docs/phase_4_5a_documentation.md §1/§5), not a genuine
no-arbitrage zero curve. Nothing in this module changes that; it just
describes the resulting curve's shape smoothly. Read every parameter and
residual below as describing THAT curve, not a fully independent ground
truth.

WHAT'S ACTUALLY BEING FIT -- ALL of Part A's bootstrapped points, not
just MOF's original ~12-15 quoted tenors. bootstrap_zero_curve() returns
one row per semiannual grid point (plus sub-1Y money-market points) --
most of these are not independent MOF observations, but points Part A
itself generated by straight-line-interpolating the (treated-as-par)
input curve before bootstrapping. Fitting against all of them, rather
than only the ~12-15 real tenors, means the reported RMSE partly measures
how well a smooth parametric curve can reproduce Part A's own
straight-line interpolation -- including the artificial "kinks" at MOF's
real tenor points where one interpolated straight segment meets the next
(most visible across the 10Y-20Y-30Y-40Y gaps). This is disclosed, not
hidden: residuals_at_original_tenors() (below) isolates the residuals at
MOF's actual quoted tenors specifically, which is the more meaningful
diagnostic for "how well does this parametric curve match the real
data," and docs/phase_4_5b_documentation.md reports both.

MODELS.

Nelson-Siegel (4 params -- beta0, beta1, beta2, tau):

    y(m) = beta0
         + beta1 * f1(m, tau)
         + beta2 * (f1(m, tau) - exp(-m/tau))

    where f1(m, tau) = (1 - exp(-m/tau)) / (m/tau)

Conventional interpretation: beta0 = long-run level (f1 -> 0 as m -> inf,
so beta0 is the asymptotic rate); beta1 = short-term component (f1 -> 1
as m -> 0, so beta0+beta1 is the instantaneous short rate) -- often read
as a slope factor since it decays away at long maturities; beta2 = a
medium-term "hump" component, governed by the same tau as beta1; tau =
the decay rate controlling both where beta1's influence fades and where
beta2's hump is centered (the hump peaks near m = tau).

Svensson (6 params -- beta0, beta1, beta2, beta3, tau1, tau2): identical
to Nelson-Siegel, plus a SECOND hump term on its own decay parameter:

    y(m) = beta0
         + beta1 * f1(m, tau1)
         + beta2 * (f1(m, tau1) - exp(-m/tau1))
         + beta3 * (f1(m, tau2) - exp(-m/tau2))

The second hump (beta3, tau2) is what lets Svensson describe a curve with
two humps/inflections instead of one -- conventionally motivated for
curves with a complex long end, which is plausibly relevant given Japan's
ultra-long segment, but THIS MODULE DOESN'T ASSUME THAT: both models are
fit and compared on actual RMSE (see docs/phase_4_5b_documentation.md for
which one wins here, and specifically WHERE the improvement comes from --
it isn't necessarily where a "Japan has a complicated long end" prior
would predict).

OPTIMIZATION -- GRID SEARCH OVER TAU, LINEAR LEAST SQUARES FOR THE
BETAS, NOT JOINT NONLINEAR OPTIMIZATION. For any FIXED tau (or tau1,
tau2), y(m) is LINEAR in the betas -- the hump functions f1, f2, (f3) are
just fixed columns of a design matrix once tau is fixed, so the betas
that minimize squared error are a single ordinary least squares solve
(np.linalg.lstsq), not an iterative search. This is both faster and far
more numerically stable than jointly optimizing all parameters at once:
tau/lambda decay parameters are notoriously unstable under naive
unbounded nonlinear optimization (the phase brief's own caution) --
concretely, a gradient-based optimizer can walk tau to an implausible
extreme (near-zero or near-infinite) chasing a marginal, poorly-
identified improvement, or fail to converge at all, especially for
Svensson where tau1 and tau2 can trade off against each other. Fixing tau
on a grid and solving the betas in closed form at every grid point avoids
this entirely: only ONE genuinely nonlinear dimension (or two, for
Svensson) is ever searched, and it's searched exhaustively over bounded,
sensible values rather than trusted to a gradient step.

No scipy dependency needed -- this project has none installed, and this
grid-search-plus-linear-least-squares approach needs only numpy, matching
the same no-heavy-dependency-for-one-use reasoning already applied to
scikit-learn (docs/phase_4b_documentation.md §1.2) and matplotlib
(docs/phase_3c_documentation.md §1.4).

TAU BOUNDS AND TWO-STAGE (COARSE THEN REFINED) GRID SEARCH. Bounds
[TAU_MIN, TAU_MAX] = [0.05, 50.0] years are chosen to span well below the
shortest maturity this project's curves ever quote (money-market tenors
under 1 year) to comfortably beyond the longest (40 years) -- wide enough
that a real optimum is very unlikely to sit outside it, narrow enough to
keep the grid a meaningful search rather than an unbounded one (the
phase brief's own "impose bounds" instruction). Each fit runs a COARSE
log-spaced grid across the full bounds first, then a FINER linear grid
zoomed into a window around the coarse optimum -- a standard two-stage
pattern-search refinement, still using only closed-form linear least
squares at every point, no gradient method anywhere.

CONVERGENCE -- CHECKED AND REPORTED, NOT ASSUMED. Since this is a grid
search, not an iterative optimizer, "convergence" means something
concrete and checkable: did the refined best tau (or tau1, tau2) land
strictly inside the search bounds, or at their edge? A result sitting at
TAU_MIN or TAU_MAX means the search couldn't find a genuine interior
minimum within the space actually explored -- the honest report in that
case is "not converged within these bounds," not a silently-accepted
boundary value. Every fit result's `converged` field records this
directly, and docs/phase_4_5b_documentation.md reports whether it held
on this project's real data (see also
tests/test_curve_fitting.py::test_convergence_is_actually_checked_not_just_true_by_construction).
"""

from __future__ import annotations

from dataclasses import dataclass

import numpy as np
import pandas as pd

from data.jgb_curve_loader import load_jgb_curve
from models.bootstrap import bootstrap_zero_curve

# See module docstring "TAU BOUNDS" -- shared by both models for one
# consistent, documented search space.
TAU_MIN = 0.05
TAU_MAX = 50.0

NS_COARSE_GRID_POINTS = 400
NS_REFINE_GRID_POINTS = 200

# Svensson's grid is 2-D (tau1 x tau2) with tau2 > tau1 enforced (see
# module docstring) -- kept coarser than NS's 1-D grid purely for runtime
# (150x150, ~11k valid combinations after the tau2>tau1 filter, each one
# a single closed-form 4-column least-squares solve: comfortably under a
# second on this project's data).
SVENSSON_COARSE_GRID_POINTS = 150
SVENSSON_REFINE_GRID_POINTS = 60

# How far the refined (stage-2) grid zooms in around the coarse optimum,
# as a multiplicative window -- e.g. 0.5 means the refine grid spans
# [coarse_best / 2, coarse_best * 2], clipped back to [TAU_MIN, TAU_MAX].
REFINE_WINDOW_MULTIPLE = 2.0


def hump_factors(tau: float, maturities: np.ndarray) -> tuple[np.ndarray, np.ndarray]:
    """f1(m, tau) = (1 - exp(-m/tau)) / (m/tau), and f2 = f1 - exp(-m/tau)
    (the Nelson-Siegel "slope" and "curvature" basis functions -- Svensson
    reuses the same f1/f2 shape a second time on tau2, module docstring).

    Public (not underscore-prefixed) because models/diebold_li.py reuses
    this exact function for its own fixed-tau design matrix -- one
    implementation of the NS basis functions, not two (Phase 4B addition;
    docs/phase_4_5b_dl_documentation.md).

    f1's 0/0 limit as m/tau -> 0 is 1.0 (L'Hopital) -- guarded via
    np.where rather than left to raise a divide-by-zero warning. Every
    maturity this project ever passes in is > 0 (the shortest MOF tenor is
    1 month), so this guard is defensive, not load-bearing on real data.
    """
    x = maturities / tau
    safe_x = np.where(x > 1e-7, x, 1.0)  # avoids an actual 0/0 while the branch is discarded below
    exp_neg_x = np.exp(-x)
    f1 = np.where(x > 1e-7, (1.0 - exp_neg_x) / safe_x, 1.0)
    f2 = f1 - exp_neg_x
    return f1, f2


def _ns_design_matrix(tau: float, maturities: np.ndarray) -> np.ndarray:
    f1, f2 = hump_factors(tau, maturities)
    return np.column_stack([np.ones_like(maturities), f1, f2])


def _svensson_design_matrix(tau1: float, tau2: float, maturities: np.ndarray) -> np.ndarray:
    f1, f2 = hump_factors(tau1, maturities)
    _, f3 = hump_factors(tau2, maturities)
    return np.column_stack([np.ones_like(maturities), f1, f2, f3])


def _fit_betas(design_matrix: np.ndarray, targets: np.ndarray) -> tuple[np.ndarray, float]:
    """Ordinary least squares, betas given a FIXED design matrix (i.e. a
    fixed tau) -- see module docstring "OPTIMIZATION". Returns (betas, sse)."""
    betas, *_ = np.linalg.lstsq(design_matrix, targets, rcond=None)
    fitted = design_matrix @ betas
    sse = float(np.sum((targets - fitted) ** 2))
    return betas, sse


def _grid_search_ns_tau(maturities: np.ndarray, targets: np.ndarray) -> tuple[float, bool]:
    """Two-stage (coarse, then refined) grid search over tau for
    Nelson-Siegel. Returns (best_tau, converged) -- converged is False iff
    the refined best sits at the outer edge of [TAU_MIN, TAU_MAX] (module
    docstring "CONVERGENCE")."""
    coarse_grid = np.geomspace(TAU_MIN, TAU_MAX, NS_COARSE_GRID_POINTS)
    coarse_sse = np.array([_fit_betas(_ns_design_matrix(t, maturities), targets)[1] for t in coarse_grid])
    coarse_best = coarse_grid[int(np.argmin(coarse_sse))]

    refine_lo = max(TAU_MIN, coarse_best / REFINE_WINDOW_MULTIPLE)
    refine_hi = min(TAU_MAX, coarse_best * REFINE_WINDOW_MULTIPLE)
    refine_grid = np.linspace(refine_lo, refine_hi, NS_REFINE_GRID_POINTS)
    refine_sse = np.array([_fit_betas(_ns_design_matrix(t, maturities), targets)[1] for t in refine_grid])
    best_tau = float(refine_grid[int(np.argmin(refine_sse))])

    converged = not (np.isclose(best_tau, TAU_MIN) or np.isclose(best_tau, TAU_MAX))
    return best_tau, converged


def _grid_search_svensson_taus(maturities: np.ndarray, targets: np.ndarray) -> tuple[float, float, bool]:
    """Two-stage grid search over (tau1, tau2) for Svensson, with tau2 >
    tau1 enforced throughout (module docstring -- avoids the near-
    collinear, poorly-identified region where the two hump terms compete
    for the same shape). Returns (best_tau1, best_tau2, converged)."""

    def _best_over_grid(grid: np.ndarray) -> tuple[float, float, float]:
        best_sse, best_t1, best_t2 = np.inf, grid[0], grid[-1]
        for t1 in grid:
            for t2 in grid:
                if t2 <= t1:
                    continue
                _, sse = _fit_betas(_svensson_design_matrix(t1, t2, maturities), targets)
                if sse < best_sse:
                    best_sse, best_t1, best_t2 = sse, t1, t2
        return best_t1, best_t2, best_sse

    coarse_grid = np.geomspace(TAU_MIN, TAU_MAX, SVENSSON_COARSE_GRID_POINTS)
    coarse_t1, coarse_t2, _ = _best_over_grid(coarse_grid)

    refine_grid1 = np.linspace(
        max(TAU_MIN, coarse_t1 / REFINE_WINDOW_MULTIPLE),
        min(TAU_MAX, coarse_t1 * REFINE_WINDOW_MULTIPLE),
        SVENSSON_REFINE_GRID_POINTS,
    )
    refine_grid2 = np.linspace(
        max(TAU_MIN, coarse_t2 / REFINE_WINDOW_MULTIPLE),
        min(TAU_MAX, coarse_t2 * REFINE_WINDOW_MULTIPLE),
        SVENSSON_REFINE_GRID_POINTS,
    )
    # Refine each dimension over the union of both refine grids (rather
    # than the two independently), so a coarse-stage tau1/tau2 that were
    # close together still get a fair joint refinement.
    refine_grid = np.union1d(refine_grid1, refine_grid2)
    best_t1, best_t2, _ = _best_over_grid(refine_grid)

    converged = not any(
        np.isclose(t, bound) for t in (best_t1, best_t2) for bound in (TAU_MIN, TAU_MAX)
    )
    return float(best_t1), float(best_t2), converged


def _extract_target(zero_curve: pd.DataFrame, min_points: int) -> tuple[np.ndarray, np.ndarray]:
    if "zero_rate" not in zero_curve.columns:
        raise ValueError(
            "zero_curve is missing a 'zero_rate' column -- pass a "
            "models.bootstrap.bootstrap_zero_curve() result, not a par curve"
        )
    if len(zero_curve) < min_points:
        raise ValueError(
            f"zero_curve has only {len(zero_curve)} point(s), need at least {min_points} "
            "to fit this model"
        )
    sorted_curve = zero_curve.sort_values("maturity_years").reset_index(drop=True)
    return sorted_curve["maturity_years"].to_numpy(dtype=float), sorted_curve["zero_rate"].to_numpy(dtype=float)


@dataclass(frozen=True)
class NelsonSiegelFitResult:
    """One Nelson-Siegel fit -- frozen, a snapshot of one zero curve's fit.

    tenors / target_rates : the fit's own x/y, exactly as taken from the
        input zero curve (module docstring -- ALL of its rows, not just
        MOF's original tenors).
    beta0, beta1, beta2, tau : the fitted parameters (module docstring for
        their conventional interpretation).
    fitted_rates : the model's own rate at each of `tenors`.
    converged : False iff the tau grid search landed at TAU_MIN/TAU_MAX
        (module docstring "CONVERGENCE") -- check this before trusting tau.
    """

    tenors: np.ndarray
    target_rates: np.ndarray
    beta0: float
    beta1: float
    beta2: float
    tau: float
    fitted_rates: np.ndarray
    converged: bool

    @property
    def rmse_bp(self) -> float:
        """RMSE against `target_rates`, in basis points -- computed on the
        fly from the stored arrays (same reasoning as every other derived
        property in this project, e.g. docs/phase_4b_documentation.md
        §1.4) so it can never drift out of sync with them."""
        return float(np.sqrt(np.mean((self.target_rates - self.fitted_rates) ** 2)) * 10000.0)

    def rate_at(self, maturity_years):
        """The fitted Nelson-Siegel rate at an arbitrary maturity (scalar
        or array-like) -- evaluates the closed-form formula directly from
        the stored parameters, valid for any maturity > 0, not just the
        points this fit was run on."""
        m = np.asarray(maturity_years, dtype=float)
        f1, f2 = hump_factors(self.tau, m)
        return self.beta0 + self.beta1 * f1 + self.beta2 * f2


@dataclass(frozen=True)
class SvenssonFitResult:
    """One Svensson fit -- same shape as NelsonSiegelFitResult, plus the
    second hump term (beta3, tau2). See module docstring for the model
    and its parameters' interpretation."""

    tenors: np.ndarray
    target_rates: np.ndarray
    beta0: float
    beta1: float
    beta2: float
    beta3: float
    tau1: float
    tau2: float
    fitted_rates: np.ndarray
    converged: bool

    @property
    def rmse_bp(self) -> float:
        return float(np.sqrt(np.mean((self.target_rates - self.fitted_rates) ** 2)) * 10000.0)

    def rate_at(self, maturity_years):
        m = np.asarray(maturity_years, dtype=float)
        f1, f2 = hump_factors(self.tau1, m)
        _, f3 = hump_factors(self.tau2, m)
        return self.beta0 + self.beta1 * f1 + self.beta2 * f2 + self.beta3 * f3


def fit_nelson_siegel(zero_curve: pd.DataFrame) -> NelsonSiegelFitResult:
    """Fit Nelson-Siegel (4 parameters, one of them -- tau -- found by
    grid search, the other three by closed-form least squares at that tau;
    module docstring "OPTIMIZATION") to a bootstrapped zero curve.

    Parameters
    ----------
    zero_curve : a DataFrame with columns [maturity_years, zero_rate] --
        the shape models.bootstrap.bootstrap_zero_curve() returns. Fitting
        this module against a par curve instead is a deliberate choice
        this function does NOT support (module docstring "WHY FIT THE
        ZERO CURVE").

    Raises
    ------
    ValueError : zero_curve lacks a zero_rate column, or has fewer than 4
        points (fewer than this model's own parameter count).
    """
    tenors, targets = _extract_target(zero_curve, min_points=4)
    tau, converged = _grid_search_ns_tau(tenors, targets)
    betas, _ = _fit_betas(_ns_design_matrix(tau, tenors), targets)
    fitted = _ns_design_matrix(tau, tenors) @ betas

    return NelsonSiegelFitResult(
        tenors=tenors,
        target_rates=targets,
        beta0=float(betas[0]),
        beta1=float(betas[1]),
        beta2=float(betas[2]),
        tau=tau,
        fitted_rates=fitted,
        converged=converged,
    )


def fit_svensson(zero_curve: pd.DataFrame) -> SvenssonFitResult:
    """Fit Svensson (6 parameters, two -- tau1, tau2 -- found by 2-D grid
    search, the other four by closed-form least squares at that pair;
    module docstring "OPTIMIZATION") to a bootstrapped zero curve. See
    fit_nelson_siegel for the shared parameters/raises.
    """
    tenors, targets = _extract_target(zero_curve, min_points=6)
    tau1, tau2, converged = _grid_search_svensson_taus(tenors, targets)
    betas, _ = _fit_betas(_svensson_design_matrix(tau1, tau2, tenors), targets)
    fitted = _svensson_design_matrix(tau1, tau2, tenors) @ betas

    return SvenssonFitResult(
        tenors=tenors,
        target_rates=targets,
        beta0=float(betas[0]),
        beta1=float(betas[1]),
        beta2=float(betas[2]),
        beta3=float(betas[3]),
        tau1=tau1,
        tau2=tau2,
        fitted_rates=fitted,
        converged=converged,
    )


def residuals_bp(fit_result: NelsonSiegelFitResult | SvenssonFitResult) -> pd.Series:
    """(target - fitted) in basis points, one entry per fit point, indexed
    by maturity_years -- shared by both result types since they carry
    identically-named tenors/target_rates/fitted_rates fields."""
    return pd.Series(
        (fit_result.target_rates - fit_result.fitted_rates) * 10000.0,
        index=pd.Index(fit_result.tenors, name="maturity_years"),
        name="residual_bp",
    )


def residuals_at_original_tenors(
    fit_result: NelsonSiegelFitResult | SvenssonFitResult,
    par_curve: pd.DataFrame,
) -> pd.Series:
    """residuals_bp(fit_result), restricted to the maturities that were
    genuinely quoted in `par_curve` (MOF's real tenors) rather than
    generated by Part A's own interpolation (module docstring "WHAT'S
    ACTUALLY BEING FIT") -- the more meaningful diagnostic of the two.
    """
    all_residuals = residuals_bp(fit_result)
    original_tenors = np.sort(par_curve["maturity_years"].to_numpy(dtype=float))
    mask = np.isin(np.round(all_residuals.index.to_numpy(), 6), np.round(original_tenors, 6))
    return all_residuals.loc[mask]


if __name__ == "__main__":
    curve = load_jgb_curve()
    zero_curve = bootstrap_zero_curve(curve)

    ns = fit_nelson_siegel(zero_curve)
    sv = fit_svensson(zero_curve)

    print()
    print(f"Fit against the bootstrapped zero curve: {len(zero_curve)} points, "
          f"{zero_curve['maturity_years'].min():.3f}Y to {zero_curve['maturity_years'].max():.1f}Y")

    print()
    print("Nelson-Siegel (4 parameters):")
    print(f"  beta0 (long-run level)      = {ns.beta0:+.4%}")
    print(f"  beta1 (short-term/slope)    = {ns.beta1:+.4%}")
    print(f"  beta2 (medium-term/hump)    = {ns.beta2:+.4%}")
    print(f"  tau   (decay)               = {ns.tau:.3f} years")
    print(f"  RMSE (all {len(ns.tenors)} fit points)      = {ns.rmse_bp:.3f}bp")
    print(f"  converged (tau inside [{TAU_MIN}, {TAU_MAX}]) = {ns.converged}")

    print()
    print("Svensson (6 parameters):")
    print(f"  beta0 (long-run level)      = {sv.beta0:+.4%}")
    print(f"  beta1 (short-term/slope)    = {sv.beta1:+.4%}")
    print(f"  beta2 (medium-term/hump 1)  = {sv.beta2:+.4%}")
    print(f"  beta3 (medium-term/hump 2)  = {sv.beta3:+.4%}")
    print(f"  tau1  (decay, hump 1)       = {sv.tau1:.3f} years")
    print(f"  tau2  (decay, hump 2)       = {sv.tau2:.3f} years")
    print(f"  RMSE (all {len(sv.tenors)} fit points)      = {sv.rmse_bp:.3f}bp")
    print(f"  converged (tau1, tau2 inside [{TAU_MIN}, {TAU_MAX}]) = {sv.converged}")

    print()
    better = "Svensson" if sv.rmse_bp < ns.rmse_bp else "Nelson-Siegel"
    print(f"-> {better} fits this curve better ({min(sv.rmse_bp, ns.rmse_bp):.3f}bp vs. "
          f"{max(sv.rmse_bp, ns.rmse_bp):.3f}bp RMSE).")

    print()
    print("Residuals at MOF's ORIGINAL quoted tenors (the meaningful subset --")
    print("see module docstring 'WHAT'S ACTUALLY BEING FIT'):")
    ns_orig = residuals_at_original_tenors(ns, curve)
    sv_orig = residuals_at_original_tenors(sv, curve)
    comparison = pd.DataFrame({"NS_resid_bp": ns_orig, "Svensson_resid_bp": sv_orig})
    print(comparison.to_string(float_format=lambda v: f"{v:+7.2f}"))

    ultra_long_mask = comparison.index >= 20.0
    print()
    print("Ultra-long (>=20Y) residuals -- the segment this project's portfolio")
    print("is most concentrated in (docs/phase_3c_documentation.md):")
    print(comparison.loc[ultra_long_mask].to_string(float_format=lambda v: f"{v:+7.2f}"))
